### ISSUE TITLE
Concatenate instead of add

### ISSUE THREAD

**Issue by tanayag** [kailashahirwar/tryondiffusion#24]
I made a little mistake while implementing the UNet architecture. Instead of concatenating, I added(elementwise summation) the channels in UNet's skip connections. 

Ideally, we must concatenate them channel-wise and reduce the channels during convolution. It's a straightforward fix. I am creating the issue to keep track of and fix the problem before training.

**Comment by rsamf** [comment]
I had the impression that we need to concat in the skip connections too, but now reading the paper closely, I see something else. See Appendix A.1. Parallel-UNet. 

"The residual blocks used in each scale have a main pathway of GroupNorm→swish→conv→GroupNorm→swish→conv. The input to the residual block is processed by a separate convolution layer and added to added to the output of the main pathway as the skip connection." 

I think this makes more sense now because if we concat, then the number of channels becomes quite large. We in fact, may need to close this issue and create a new once. I'm currently trying to understand Group Normalization, the swish activation model, and what the whole residual block will look like.
